server:
  port: 8010

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c


logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
spring:
  application:
    name: category
  data:
    mongodb:
      authentication-database: admin
      username: bogdan
      password: password
      database: category_database
      port: 27018
      host: localhost
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true