apiVersion: v1
kind: Service
metadata:
  name: angular-app
spec:
  type: ClusterIP
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      name: ui-port
      port: 4200
      targetPort: 4200
  type: LoadBalancer
