apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: promotion
  name: promotion
spec:
  ports:
    - name: "8118"
      port: 8118
      targetPort: 8118
  selector:
    io.kompose.service: promotion
status:
  loadBalancer: {}
