spring:
  datasource:
    url: "jdbc:postgresql://localhost:5434/Security"
    username: "bogdan"
    password: "pass"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"

  application:
    name: security

  rabbitmq:
    addresses: localhost:5672

server:
  port: 8502

management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        security: TRACE
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
