services:
  mongodb-category:
    image: mongo:latest
    restart: always
    hostname: mongo-category
    environment:
      MONGO_INITDB_ROOT_USERNAME: bogdan
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: category_database
    ports:
      - "27018:27017"
    volumes:
      - category-data:/data/category/db
    networks:
      - mongodb-network

  compass:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "28082:8002"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-category
      ME_CONFIG_BASICAUTH_USERNAME: bogdan
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: bogdan
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      #ME_CONFIG_MONGODB_URL: mongo://bogdan:password@mongo-category:27017/

    depends_on:
      - mongodb-category
    networks:
      - mongodb-network

volumes:
  category-data:

networks:
  mongodb-network:
    driver: bridge
