services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bogdan
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product_database
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/product/db
    networks:
      - mongodb-network

  compass:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: bogdan
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: bogdan
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongo://bogdan:password@mongodb:27017/

    volumes:
      - compass-data:/root/.mongodb/compass/
    depends_on:
      - mongodb
    networks:
      - mongodb-network

volumes:
  mongodb-data:
  compass-data:

networks:
  mongodb-network:
    driver: bridge
