server:
  port: 8056

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: inventory

database:
  server-ip: localhost
  port: 6380

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true