apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: review
  name: review
spec:
  ports:
    - name: "8395"
      port: 8395
      targetPort: 8395
  selector:
    io.kompose.service: review
status:
  loadBalancer: {}
