apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory
  name: inventory
spec:
  ports:
    - name: "8056"
      port: 8056
      targetPort: 8056
  selector:
    io.kompose.service: inventory
status:
  loadBalancer: {}
