server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c


logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://bogdan:password@localhost:27017/product_database?authSource=admin
      auto-index-creation: true
  application:
    name: product


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
