apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-persistence-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-persistence-deployment  # Name of your Deployment
  minReplicas: 1
  maxReplicas: 5  # Adjust based on your requirements
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80  # 80% CPU utilization
