apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: cart-persistence
  name: cart-persistence
spec:
  ports:
    - name: "8256"
      port: 8256
      targetPort: 8256
  selector:
    io.kompose.service: cart-persistence
status:
  loadBalancer: {}
