apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: notification
  name: notification
spec:
  ports:
    - name: "8110"
      port: 8110
      targetPort: 8110
  selector:
    io.kompose.service: notification
status:
  loadBalancer: {}
