version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: bogdan
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: review_database
    ports:
      - "27021:27017"
    volumes:
      - mongodb-data:/data/client-info/db
    networks:
      - mongodb-network
  review_application:
    image: review:1.0-SNAPSHOT
    depends_on: [mongodb]
    networks:
      - mongodb-network
  eureka_server:
    image: bogdansoftware/eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - mongodb-network


volumes:
    mongodb-data:

networks:
  mongodb-network:
    driver: bridge
