server:
  port: 8110

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c

logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: notification
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-key:
    internal-notification: internal.notification.routing-key

twilio:
  account-sid: 'AC6066756e9e21f73382af7a0f85716a52'
  auth-token: '4611d61801aefedd9d5ad392b71a6b66'
  sender-number: '+16562163138'

mail:
  host: 'smtp.gmail.com'
  port: 587
  username: 'everything.online.office@gmail.com'
  password: "plelpfzxsyrdasey"
